OSTYPE := $(shell uname -s)

BIN_DIR = /home/yingyin/workspace/tabletop/tabletop_kinect

INC_DIRS = . /usr/include/ni /usr/lib/jvm/java-6-sun-1.6.0.24/include \
					  /usr/lib/jvm/java-6-sun-1.6.0.24/include/linux

SRC_FILES = *.cpp

LIB_NAME = openni-java-wrapper

USED_LIBS += OpenNI

CFLAGS = -Wno-deprecated

include ../CommonMakefile

