/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_yingyin_tabletop_OpenNIWrapper */

#ifndef _Included_edu_mit_yingyin_tabletop_OpenNIWrapper
#define _Included_edu_mit_yingyin_tabletop_OpenNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_mit_yingyin_tabletop_OpenNIWrapper
 * Method:    initFromXmlFile
 * Signature: (Ljava/nio/IntBuffer;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_mit_yingyin_tabletop_OpenNIWrapper_initFromXmlFile
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
