/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_yingyin_tabletop_models_PartialOpenNIDevice */

#ifndef _Included_edu_mit_yingyin_tabletop_models_PartialOpenNIDevice
#define _Included_edu_mit_yingyin_tabletop_models_PartialOpenNIDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_mit_yingyin_tabletop_models_PartialOpenNIDevice
 * Method:    loadFile
 * Signature: (Ljava/lang/String;Ljava/nio/IntBuffer;I)V
 */
JNIEXPORT void JNICALL Java_edu_mit_yingyin_tabletop_models_PartialOpenNIDevice_loadFile
  (JNIEnv *, jclass, jstring, jobject, jint);

/*
 * Class:     edu_mit_yingyin_tabletop_models_PartialOpenNIDevice
 * Method:    initFromXmlFile
 * Signature: (Ljava/nio/IntBuffer;Ljava/lang/String;Ljava/nio/IntBuffer;Ljava/nio/IntBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_mit_yingyin_tabletop_models_PartialOpenNIDevice_initFromXmlFile
  (JNIEnv *, jobject, jobject, jstring, jobject, jobject);

/*
 * Class:     edu_mit_yingyin_tabletop_models_PartialOpenNIDevice
 * Method:    waitAnyUpdateAll
 * Signature: (Ljava/nio/IntBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_mit_yingyin_tabletop_models_PartialOpenNIDevice_waitAnyUpdateAll
  (JNIEnv *, jobject, jobject);

/*
 * Class:     edu_mit_yingyin_tabletop_models_PartialOpenNIDevice
 * Method:    waitDepthUpdateAll
 * Signature: (Ljava/nio/IntBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_mit_yingyin_tabletop_models_PartialOpenNIDevice_waitDepthUpdateAll
  (JNIEnv *, jobject, jobject);

/*
 * Class:     edu_mit_yingyin_tabletop_models_PartialOpenNIDevice
 * Method:    getDepthMap
 * Signature: (Ljava/nio/IntBuffer;Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_edu_mit_yingyin_tabletop_models_PartialOpenNIDevice_getDepthMap
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     edu_mit_yingyin_tabletop_models_PartialOpenNIDevice
 * Method:    release
 * Signature: (Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_edu_mit_yingyin_tabletop_models_PartialOpenNIDevice_release
  (JNIEnv *, jobject, jobject);

/*
 * Class:     edu_mit_yingyin_tabletop_models_PartialOpenNIDevice
 * Method:    convertDepthProjectiveToWorld
 * Signature: (Ljava/nio/IntBuffer;Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_edu_mit_yingyin_tabletop_models_PartialOpenNIDevice_convertDepthProjectiveToWorld
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
